services:
  mariadb:
    container_name: inception-mariadb
    build: requirements/mariadb
    networks:
      - wordpress-network
    volumes:
      - mariadb-volume:/var/mariadb
    secrets:
      - source: database-secret
        target: database.env
      - source: wordpress-secret
        target: wordpress.env
  wordpress:
    container_name: inception-wordpress
    build: requirements/wordpress
    networks:
      - wordpress-network
    volumes:
      - wordpress-volume:/var/www/html/
    depends_on:
      - mariadb
    secrets:
      - source: database-secret
        target: .env
  nginx:
    container_name: inception-nginx
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - wordpress-network
    volumes:
      - wordpress-volume:/var/www/html/
    depends_on:
      - wordpress
    secrets:
      - source: nginx-secret
        target: .env
volumes:
  mariadb-volume:
    driver: local
  wordpress-volume:
    driver: local
networks:
  wordpress-network: {}
secrets:
  database-secret:
    file: ./database.env
  nginx-secret:
    file: ./nginx.env
  wordpress-secret:
    file: ./wordpress.env
