services:
  mariadb:
    build: requirements/mariadb
    networks:
      - wordpress-network
    volumes:
      - mariadb-volume:/var/mariadb
  wordpress:
    build: requirements/wordpress
    networks:
      - wordpress-network
    volumes:
      - wordpress-volume:/usr/www/html/
    depends_on:
      - mariadb
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - wordpress-network
    volumes:
      - wordpress-volume:/usr/share/nginx/html/
    depends_on:
      - wordpress
volumes:
  mariadb-volume:
    driver: local
  wordpress-volume:
    driver: local
networks:
  wordpress-network: {}
